name: "[CI] Term Customizer"
on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_app:
    name: Build test application
    uses: Platoniq/gha-decidim-module/.github/workflows/build_app.yml@main
    secrets: inherit
  main:
    needs: build_app
    name: Tests
    uses: ./.github/workflows/test_app.yml
    with:
      test_command: "bundle exec rspec --pattern './spec/**/*_spec.rb'"
    secrets: inherit
