on:
  workflow_call:
    inputs:
      use-cached-app:
        description: Loads the generated test application from the cache also loads the DB schema for the cached app.
        required: false
        default: true
      load-schema:
        description: Loads the DB schema in case the database has not been initialized.
        required: false
        default: false
jobs:
  test_rspec:
    name: Test app (RSpec)
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    env:
      CI: "true"
      CODECOV: "true" # legacy
      SIMPLECOV: "true"
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RUBYOPT: '-W:no-deprecated'
    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
     - run: sudo apt-get install imagemagick
       name: Install ImageMagick
       shell: "bash"
     - uses: actions/checkout@v4
       with:
         fetch-depth: 1
     # Note that the cache action needs to come after the checkout because it
     # deletes the whole folder.
     - uses: actions/cache@v4
       id: decidim-app-cache
       with:
         path: ./spec/decidim_dummy_app/
         key: decidim-app-${{ github.sha }}
         restore-keys: decidim-app-${{ github.sha }}
       if: ${{ fromJSON(inputs.use-cached-app) }}
     - uses: ruby/setup-ruby@v1
       with:
         bundler-cache: true
     - uses: nanasess/setup-chromedriver@v2
     - run: bundle exec rails db:purge db:schema:load
       name: Load DB schema
       shell: "bash"
       working-directory: ./spec/decidim_dummy_app/
       env:
         RAILS_ENV: test
         DISABLE_SPRING: 1
       if: ${{ fromJSON(inputs.use-cached-app) || fromJSON(inputs.load-schema)}}
     - run: bundle exec rspec
       name: RSpec
       shell: "bash"
       env:
         DISABLE_SPRING: 1
     - uses: codecov/codecov-action@v3
     - uses: actions/upload-artifact@v4
       if: always()
       with:
         name: screenshots
         path: ./spec/decidim_dummy_app/tmp/screenshots
         if-no-files-found: ignore
